Repository hyperledger-identus/apollo, pull requests merged in 2023-12, with the labels that each got.

#122 build: update Kotlin to 1.9.20
  .github/workflows/pull-request.yml
  .releaserc.yml
  README.md
  apollo/build.gradle.kts
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/derivation/Mnemonic.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/secp256k1/ECDH.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/secp256k1/ECDSA.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/secp256k1/Secp256k1.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/securerandom/SecureRandom.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/utils/CArrayPointerExt.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/utils/KMMEdPrivateKey.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/utils/KMMEdPublicKey.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/utils/KMMX25519PrivateKey.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/utils/ToPlatform.kt
  apollo/src/appleTest/kotlin/io/iohk/atala/prism/apollo/secp256k1/Secp256k1Tests.kt
  apollo/src/iosSimulatorArm64Main/kotlin/io/iohk/atala/prism/apollo/Platform.kt
  apollo/src/macosMain/kotlin/io/iohk/atala/prism/apollo/Platform.kt
  apollo/src/macosX64Main/kotlin/io/iohk/atala/prism/apollo/Platform.kt
  apollo/src/nativeInterop/cinterop/IOHKCryptoKit.def
  apollo/src/nativeInterop/cinterop/IOHKSecureRandomGeneration.def
  apollo/src/nativeInterop/cinterop/SwiftCryptoKit.def
  build.gradle.kts
  iOSLibs/IOHKCryptoKit/IOHKCryptoKit.xcodeproj/project.pbxproj
  secp256k1-kmp/build.gradle.kts
  secp256k1-kmp/src/commonMain/kotlin/fr/acinq/secp256k1/Hex.kt
  secp256k1-kmp/src/commonMain/kotlin/fr/acinq/secp256k1/Secp256k1.kt
  secp256k1-kmp/src/nativeMain/kotlin/fr/acinq/secp256k1/Secp256k1Native.kt
Labels: documentation, enhancement

#126 build: Update Kotlin to 1.9.21
  .github/workflows/pull-request.yml
  README.md
  apollo/build.gradle.kts
  build.gradle.kts
Labels: enhancement

#132 build: Disable publish to all but (JVM, Android, KMP)
  apollo/build.gradle.kts
  build.gradle.kts
  secp256k1-kmp/build.gradle.kts
Labels: action

#133 fix: add documentation and release a new version
  README.md
Labels: documentation

#138 docs: Update README.md
  README.md
Labels: documentation

#139 refactor: Change PBKDF2SHA512 from class to Object
  apollo/src/androidMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
  apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
  apollo/src/commonMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
  apollo/src/jsMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
  apollo/src/jvmMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
Labels: enhancement

#140 build: update android compile sdk from 32 to 33
  apollo/build.gradle.kts
Labels: enhancement

#141 build: Enable documentation export to generated Swift/Obj-C code
  apollo/build.gradle.kts
Labels: documentation, enhancement

#142 build: Update kover version
  build.gradle.kts
Labels: enhancement
